version: '3.4'

services:
  flakjacket.discordbot.workerservice:
    image: ${DOCKER_REGISTRY-}flakjacketdiscordbotworkerservice
    build:
      context: .
      dockerfile: FlakJacket.DiscordBot.WorkerService/Dockerfile
    environment:
        - DiscordSettings__Token
        - DiscordSettings__Status=Testing!
        - DiscordSettings__ShardManagerUri=http://shardmanager
        - DiscordSettings__SetupChannelName=flakjacket
        - DiscordSettings__UpdateDelay=00:00:30
        - DiscordSettings__MaxBroadcastPosts=10
        - DiscordSettings__SourceUri=https://liveuamap.com
        - LoggerConfig__ServerUri=http://seq
        - LoggerConfig__ApiKey
    depends_on:
        - seq
        - shardmanager

  seq:
    image: datalust/seq:2021.3.6681
    ports:
        - 8080:80
    environment:
        - ACCEPT_EULA=Y
    volumes:
        - seqdata:/data

  shardmanager:
    container_name: shardmanager
    image: nickmartin1ee7/discordbotshardmanagerwebapi:latest
    environment:
        - ShardManager__MaxShards=1
        - ShardManager__InternalShards=1
    ports:
        - 8081:80

volumes:
  seqdata:
